# Generated by Django 5.0.4 on 2024-04-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('kitchen_type', models.CharField(max_length=255)),
                ('composition', models.TextField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('caloric', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dish_images')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('spice', models.PositiveIntegerField(default=0)),
                ('is_season', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.category')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'db_table': 'dish',
                'ordering': ['name'],
            },
        ),
    ]
