# Generated by Django 5.0.4 on 2024-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
