# Generated by Django 5.0.4 on 2024-04-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_name_reservation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='comments',
        ),
    ]
