# Generated by Django 5.0.4 on 2024-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(),
        ),
    ]
