name: Build Docker Container

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  test_django:
    uses: VictoriaLisova/restaurant_website/.github/workflows/testing.yml@main
  docker-build:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - uses: actions/checkout@v2