name: Build Docker Container

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test_django:
    uses: ValeriiaPataman/restaurant_website/.github/workflows/testing.yml@main
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-docker-image .
      - name: Push Docker image to registry
        run: docker push my-docker-image