name: Django Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          python manage.py test dishes
          python manage.py test reservation
          python manage.py test polls
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install Heroku CLI
#        run: curl https://cli-assets.heroku.com/install.sh | sh
#
#      - name: Auth to Heroku
#        env:
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#        run: echo ${HEROKU_API_KEY} | heroku auth:token
#
#      - name: Add Heroku remote
#        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
#
#      - name: Deploy to Heroku
#        env:
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#        run: git push heroku main:refs/heads/main --force

  deploy:
    runs-on: ubuntu-latest
    name: deploy our application to heroku
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: nyakaz73/heroku-django-deploy@v0.68
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email_address: ${{ secrets.HEROKU_EMAIL }}
          use_git: true


